#!/usr/bin/env bash

mkdir docs/c docs/i docs/r 2>/dev/null
gallery=""
for f in ecard-sample/*.png; do
  page="$(basename $f | perl -p -e 's/\.png//')"
  font="$(cat ecard-sample/config.json | jq -r '."'$page'"."font-family"')"
  if [[ "$font" == '' || "$font" == "null" ]]; then
    font="$(cat ecard-sample/config.json | jq -r '."default"."font-family"')"
  fi
  message="$(cat ecard-sample/config.json | jq -r '."'$page'"."message"')"
  if [[ "$message" == '' || "$message" == "null" ]]; then
    message="$(cat ecard-sample/config.json | jq -r '."default"."message"')"
  fi
  audio="$(cat ecard-sample/config.json | jq -r '."'$page'"."audio"')"
  background="$(cat ecard-sample/config.json | jq -r '."'$page'"."background"')"
  if [[ "$background" == '' || "$background" == "null" ]]; then
    background="$(cat ecard-sample/config.json | jq -r '."default"."background"')"
  fi
  if [[ "$background" == '' || "$background" == "null" ]]; then
    background="#f6f6f5"
  fi
  echo "|generating $page"
  cp "ecard-sample/index.html" "docs/r/$page.html"
  cp "ecard-sample/index-gen.html" "docs/c/$page.html"
  cp "$f" "docs/i/${page}.png"
  perl -pi -e 's/\{\{IMAGE\}\}/'$page'/g' docs/{r,c}/"${page}.html"
  perl -pi -e 's/\{\{FONT\}\}/'$font'/g' docs/{r,c}/"${page}.html"
  escaped_message=$(printf '%s' "$message" | sed 's/[&/\]/\\&/g')
  perl -pi -e 's/\{\{MESSAGE\}\}/'"$escaped_message"'/g' docs/{r,c}/"${page}.html"
  perl -pi -e 's/\{\{BACKGROUND\}\}/'$background'/g' docs/{r,c}/"${page}.html"
  font_uri="$(find docs/i/ -name "*${font}*.ttf" | head -n 1 | perl -p -e 's/^docs//' | perl -p -e 's/\//\\\//g')"
  if [[ "$font_uri" != "" ]]; then
    echo "|  -> custom font -> $font, $font_uri"
    perl -pi -e 's/\{\{FONT_BLOCK\}\}/\@font-face { font-family: "'$font'"; src: url("'$font_uri'"); }/g' docs/{r,c}/"${page}.html"
    perl -pi -e 's/\{\{FONT_BLOCK\}\}//g' docs/{r,c}/"${page}.html"
  else
    perl -pi -e 's/\{\{FONT_BLOCK\}\}//g' docs/{r,c}/"${page}.html"
  fi
  if [[ "$audio" != '' && "$audio" != "null" ]]; then
    echo "|  -> audio -> $audio"
    perl -pi -e 's|\{\{MIDI\}\}|<audio autoplay><source src="/i/'$audio'" type="audio/mpeg"></audio>|g' docs/{r,c}/"${page}.html"
  else
    perl -pi -e 's/\{\{MIDI\}\}//g' docs/{r,c}/"${page}.html"
  fi
  curl -s "https://api.friedliver.com/57ea9fa9-c422-4a2d-b5b9-1c0092e3c0fc?page=$page&key=$FRIEDLIVER" >/dev/null 2>&1
  if [[ "$(which prettier)" ]]; then
    prettier -w docs/{r,c}/"${page}.html" >/dev/null
  else
    echo "|  -> prettier not found, skipping lint"
  fi
  gallery="$(cat ecard-sample/index-part.html | perl -p -e 's/\{\{IMAGE\}\}/'$page'/g' | perl -p -e 's/([\/\&\\])/\\$1/g' ) $gallery"
done

perl -p0i -e 's/(<!-- SOG !-->).*(<!-- EOG !-->)/$1<div class="gallery">'"$gallery"'<\/div>$2/gms' docs/index.html
prettier -w docs/index.html
